name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest   # ubuntu-latest 써도 OK
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew --version
      - run: ./gradlew test
